base/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('peoples.urls')),
    path('main/', include('main.urls'))
]

peoples/urls.py
from django.urls import path
from peoples import views

app_name = 'peoples'

urlpatterns = [
    path('', views.StudentListView.as_view(), name='student-list'),
    path('students/create/', views.StudentCreateView.as_view(), name='student-create'),
    path('students/update/<int:pk>/', views.StudentUpdateView.as_view(), name='student-edit'),
    path('students/detail/<int:pk>/', views.StudentDetailView.as_view(), name='student-detail'),
    path('stuff/', views.StuffListView.as_view(), name='stuff-list'),
    path('stuff/create/', views.StuffCreateView.as_view(), name='stuff-create'),
    path('stuff/update/<int:pk>/', views.StuffUpdateView.as_view(), name='stuff-edit'),
    path('stuff/detail/<int:pk>/', views.StuffDetailView.as_view(), name='stuff-detail'),
]

peoples/models.py
from django.db import models
from django.urls import reverse_lazy
from peoples.choices import StuffRole


class Student(models.Model):
    """
    Студент
    """

    first_name = models.CharField('Имя', max_length=256)
    last_name = models.CharField('Фамилия', max_length=256)
    date_of_birth = models.DateField('Дата рождения', blank=True, null=True)

    class Meta:
        verbose_name = 'Студент'
        verbose_name_plural = 'Студенты'
        ordering = ('-first_name',)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    def get_detail_url(self):
        return reverse_lazy('peoples:student-detail', kwargs={'pk': self.pk})

    def get_edit_url(self):
        return reverse_lazy('peoples:student-edit', kwargs={'pk': self.pk})


class Stuff(models.Model):
    """
    Сотрудник
    """

    first_name = models.CharField('Имя', max_length=256)
    last_name = models.CharField('Фамилия', max_length=256)
    role = models.IntegerField('Роль', choices=StuffRole.choices, default=StuffRole.TEACHER)
    date_of_birth = models.DateField('Дата рождения', blank=True, null=True)

    class Meta:
        verbose_name = 'Сотрудник'
        verbose_name_plural = 'Сотрудники'
        ordering = ('-first_name',)

    def __str__(self):
        return f'{self.get_role_display()} {self.first_name} {self.last_name}'

    def get_detail_url(self):
        return reverse_lazy('peoples:stuff-detail', kwargs={'pk': self.pk})

    def get_edit_url(self):
        return reverse_lazy('peoples:stuff-edit', kwargs={'pk': self.pk})

peoples/forms.py
from django import forms
from peoples.models import Student, Stuff


class StudentBaseForm(forms.ModelForm):
    """
    Базовая форма Студента
    """

    class Meta:
        model = Student
        fields = '__all__'


class StudentCreateForm(StudentBaseForm):
    """
    Форма Создание студента
    """

    pass


class StudentUpdateForm(StudentBaseForm):
    """
    Форма Редактирование студента
    """

    pass


class StuffBaseForm(forms.ModelForm):
    """
    Базовая форма сотрудника
    """

    class Meta:
        model = Stuff
        fields = '__all__'


class StuffCreateForm(StuffBaseForm):
    """
    Форма Создание сотрудника
    """

    pass


class StuffUpdateForm(StuffBaseForm):
    """
    Форма Редактирование сотрудника
    """

    pass

peoples/views.py
from django.views.generic import CreateView, UpdateView, ListView, DetailView
from peoples.forms import StudentCreateForm, StudentUpdateForm, StuffCreateForm, StuffUpdateForm
from peoples.models import Student, Stuff


class StudentCreateView(CreateView):
    """
    Создание студента
    """

    model = Student
    template_name = 'peoples/students/create.html'
    form_class = StudentCreateForm

    def get_success_url(self):
        return self.object.get_detail_url()


class StudentUpdateView(UpdateView):
    """
    Редактирование студента
    """

    model = Student
    template_name = 'peoples/students/update.html'
    form_class = StudentUpdateForm

    def get_success_url(self):
        return self.object.get_detail_url()


class StudentListView(ListView):
    """
    Список студентов
    """

    model = Student
    template_name = 'peoples/students/list.html'


class StudentDetailView(DetailView):
    """
    Просмотр студента
    """

    model = Student
    template_name = 'peoples/students/detail.html'


class StuffCreateView(CreateView):
    """
    Создание сотрудника
    """

    model = Stuff
    template_name = 'peoples/stuff/create.html'
    form_class = StuffCreateForm

    def get_success_url(self):
        return self.object.get_detail_url()


class StuffUpdateView(UpdateView):
    """
    Редактирование сотрудника
    """

    model = Stuff
    template_name = 'peoples/stuff/update.html'
    form_class = StuffUpdateForm

    def get_success_url(self):
        return self.object.get_detail_url()


class StuffListView(ListView):
    """
    Список сотрудников
    """

    model = Stuff
    template_name = 'peoples/stuff/list.html'


class StuffDetailView(DetailView):
    """
    Просмотр сотрудника
    """

    model = Stuff
    template_name = 'peoples/stuff/detail.html'

templates/peoples/students/create.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h2 class="mb-4">Добавить студента</h2>

    <form method="post">
        {% csrf_token %}
        
        <div class="mb-3">
            <label for="id_first_name" class="form-label">Имя</label>
            <input type="text" class="form-control" id="id_first_name" name="first_name" required>
        </div>

        <div class="mb-3">
            <label for="id_last_name" class="form-label">Фамилия</label>
            <input type="text" class="form-control" id="id_last_name" name="last_name" required>
        </div>

        <div class="mb-3">
            <label for="id_date_of_birth" class="form-label">Дата рождения</label>
            <input type="date" class="form-control" id="id_date_of_birth" name="date_of_birth" required>
        </div>
        <a href="{% url 'peoples:student-list' %}" class="btn btn-outline-success">Назад</a>
        <button type="submit" class="btn btn-success">Добавить студента</button>
    </form>
</div>
{% endblock %}

templates/peoples/students/detail.html
{% extends 'base.html' %}

{% block content %}
  <div class="container mt-5">
    <h2 class="mb-4">Информация о студенте</h2>

    <div class="card">
      <div class="card-body">
        <h5 class="card-title">{{ student.first_name }} {{ student.last_name }}</h5>
        <p class="card-text">Дата рождения: {{ student.date_of_birth }}</p>
      </div>
    </div>

    <div class="mt-3">
      <a href="{% url 'peoples:student-list' %}" class="btn btn-primary">Вернуться к списку студентов</a>
      <a href="{% url 'peoples:student-edit' student.pk %}" class="btn btn-warning">Редактировать</a>
    </div>
  </div>
{% endblock %}

templates/peoples/students/list.html
{% extends 'base.html' %}

{% block content %}
  <div class="container mt-5">
    <div class="d-flex justify-content-between align-items-center mb-4">
      <h2 class="mb-0">Список студентов</h2>
      <a href="{% url 'peoples:student-create' %}" class="btn btn-primary">Добавить студента</a>
    </div>

    <table class="table">
      <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Имя</th>
        <th scope="col">Фамилия</th>
        <th scope="col">Дата рождения</th>
      </tr>
      </thead>
      <tbody>
      {% for student in object_list %}
        <tr style="cursor: pointer;" onclick="window.location='{% url 'peoples:student-detail' pk=student.pk %}'">
          <th scope="row">{{ forloop.counter }}</th>
          <td>{{ student.first_name }}</td>
          <td>{{ student.last_name }}</td>
          <td>{{ student.date_of_birth }}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

templates/peoples/students/update.html
{% extends 'base.html' %}

{% block content %}
  <div class="container mt-5">
    <h2 class="mb-4">Редактировать информацию о студенте</h2>

    <form method="post">
      {% csrf_token %}

      <div class="mb-3">
        <label for="id_first_name" class="form-label">Имя</label>
        <input type="text" class="form-control" id="id_first_name" name="first_name" value="{{ object.first_name }}"
               required>
      </div>

      <div class="mb-3">
        <label for="id_last_name" class="form-label">Фамилия</label>
        <input type="text" class="form-control" id="id_last_name" name="last_name" value="{{ object.last_name }}"
               required>
      </div>

      <div class="mb-3">
        <label for="id_date_of_birth" class="form-label">Дата рождения</label>
        <input type="date" class="form-control" id="id_date_of_birth" name="date_of_birth"
               value="{% if object.date_of_birth %}{{ object.date_of_birth|date:'Y-m-d' }}{% endif %}">
      </div>

      <button type="submit" class="btn btn-primary">Сохранить изменения</button>
    </form>

    <div class="mt-3">
      <a href="{% url 'peoples:student-detail' object.pk %}" class="btn btn-secondary">Отмена</a>
    </div>
  </div>
{% endblock %}