base/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('peoples.urls')),
    path('main/', include('main.urls'))
]

main/urls.py
from django.urls import path
from main import views

app_name = 'main'

urlpatterns = [
    path('', views.DepartmentListView.as_view(), name='department-list'),
    path('departments/create/', views.DepartmentCreateView.as_view(), name='department-create'),
    path('departments/update/<int:pk>/', views.DepartmentUpdateView.as_view(), name='department-edit'),
    path('departments/detail/<int:pk>/', views.DepartmentDetailView.as_view(), name='department-detail'),
    path('faculties/', views.FacultyListView.as_view(), name='faculty-list'),
    path('faculties/create/', views.FacultyCreateView.as_view(), name='faculty-create'),
    path('faculties/update/<int:pk>/', views.FacultyUpdateView.as_view(), name='faculty-edit'),
    path('faculties/detail/<int:pk>/', views.FacultyDetailView.as_view(), name='faculty-detail'),
    path('statements/', views.StatementListView.as_view(), name='statement-list'),
    path('statements/create/', views.StatementCreateView.as_view(), name='statement-create'),
    path('statements/update/<int:pk>/', views.StatementUpdateView.as_view(), name='statement-edit'),
    path('statements/detail/<int:pk>/', views.StatementDetailView.as_view(), name='statement-detail'),
]

main/models.py
from django.db import models
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.functional import cached_property


class Faculty(models.Model):
    """
    Факультет
    """

    name = models.CharField('Название факультета', max_length=5000)
    leader = models.OneToOneField('peoples.Stuff', verbose_name='Декан', null=True, blank=True, on_delete=models.SET_NULL)
    room = models.PositiveIntegerField('Номер комнаты', default=1)
    housing = models.PositiveIntegerField('Номер корпуса', default=1)
    phone = models.CharField('Номер телефона', max_length=30, blank=True, default='Отсутствует')
    teachers = models.ManyToManyField('peoples.Stuff', verbose_name='Преподаватели', related_name='faculties')

    class Meta:
        verbose_name = 'Факультет'
        verbose_name_plural = 'Факультеты'
        ordering = ('-name',)

    def __str__(self):
        return self.name

    def get_detail_url(self):
        return reverse_lazy('main:faculty-detail', kwargs={'pk': self.pk})


class Department(models.Model):
    """
    Кафедра
    """

    name = models.CharField('Название кафедры', max_length=5000)
    leader = models.OneToOneField(
        'peoples.Stuff', verbose_name='Заведующий', related_name='department', null=True, blank=True, on_delete=models.SET_NULL
    )
    faculty = models.ForeignKey(
        'main.Faculty', verbose_name='Факультет', null=True, blank=True, on_delete=models.SET_NULL
    )
    room = models.PositiveIntegerField('Номер комнаты', default=1)
    housing = models.PositiveIntegerField('Номер корпуса', default=1)
    phone = models.CharField('Номер телефона', max_length=30, blank=True, default='Отсутствует')
    teachers = models.ManyToManyField('peoples.Stuff', verbose_name='Преподаватели', related_name='departments')

    class Meta:
        verbose_name = 'Кафедра'
        verbose_name_plural = 'Кафедры'
        ordering = ('-name',)

    def __str__(self):
        return self.name

    def get_detail_url(self):
        return reverse_lazy('main:department-detail', kwargs={'pk': self.pk})


class StudentGroup(models.Model):
    """
    Учебная группа
    """

    name = models.CharField('Название группы', max_length=5000)
    date_start = models.DateField('Дата поступления', default=timezone.now, blank=True)
    course = models.PositiveIntegerField('Курс', default=1),
    students = models.ManyToManyField('peoples.Student', verbose_name='Студенты', related_name='student_groups')

    class Meta:
        verbose_name = 'Учебная группа'
        verbose_name_plural = 'Учебные группы'
        ordering = ('-name',)

    def __str__(self):
        return self.name


class Statement(models.Model):
    """
    Ведомость
    """

    group = models.OneToOneField(
        'main.StudentGroup', verbose_name='Группа', related_name='statement', on_delete=models.CASCADE
    )
    student = models.OneToOneField(
        'peoples.Student', verbose_name='Студент', related_name='statement', on_delete=models.CASCADE
    )
    grade = models.PositiveIntegerField('Оценка', default=1)

    @cached_property
    def name(self):
        return f'Ведомость студента {self.student} группы {self.group}'

    class Meta:
        verbose_name = 'Ведомость'
        verbose_name_plural = 'Ведомости'
        ordering = ('-student',)

    def __str__(self):
        return self.name


    def get_detail_url(self):
        return reverse_lazy('main:statement-detail', kwargs={'pk': self.pk})

main/forms.py
from django import forms
from main.models import Department, Faculty, Statement


class DepartmentBaseForm(forms.ModelForm):
    """
    Базовая форма Кафедры
    """

    class Meta:
        model = Department
        fields = '__all__'


class DepartmentCreateForm(DepartmentBaseForm):
    """
    Форма Создание кафедры
    """

    pass


class DepartmentUpdateForm(DepartmentBaseForm):
    """
    Форма Редактирование кафедры
    """

    pass


class FacultyBaseForm(forms.ModelForm):
    """
    Базовая форма Факультета
    """

    class Meta:
        model = Faculty
        fields = '__all__'


class FacultyCreateForm(FacultyBaseForm):
    """
    Форма Создание Факультета
    """

    pass


class FacultyUpdateForm(FacultyBaseForm):
    """
    Форма Редактирование Факультета
    """

    pass


class StatementBaseForm(forms.ModelForm):
    """
    Базовая форма Ведомости
    """

    class Meta:
        model = Statement
        fields = '__all__'


class StatementCreateForm(StatementBaseForm):
    """
    Форма Создание Ведомости
    """

    pass


class StatementUpdateForm(StatementBaseForm):
    """
    Форма Редактирование Ведомости
    """

    pass

main/views.py
from django.views.generic import CreateView, UpdateView, ListView, DetailView

from main.forms import FacultyUpdateForm, FacultyCreateForm, DepartmentUpdateForm, DepartmentCreateForm, \
    StatementUpdateForm, StatementCreateForm
from main.models import Department, Faculty, Statement
from peoples.choices import StuffRole
from peoples.models import Stuff


class DepartmentCreateView(CreateView):
    """
    Создание Кафедры
    """

    model = Department
    template_name = 'main/departments/create.html'
    form_class = DepartmentCreateForm

    def get_success_url(self):
        return self.object.get_detail_url()


class DepartmentUpdateView(UpdateView):
    """
    Редактирование Кафедры
    """

    model = Department
    template_name = 'main/departments/update.html'
    form_class = DepartmentUpdateForm

    def get_success_url(self):
        return self.object.get_detail_url()


class DepartmentListView(ListView):
    """
    Список Кафедр
    """

    model = Department
    template_name = 'main/departments/list.html'


class DepartmentDetailView(DetailView):
    """
    Просмотр Кафедры
    """

    model = Department
    template_name = 'main/departments/detail.html'


class FacultyCreateView(CreateView):
    """
    Создание Факультета
    """

    model = Faculty
    template_name = 'main/faculties/create.html'
    form_class = FacultyCreateForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        teachers = Stuff.objects.filter(role=StuffRole.TEACHER)
        context.update({'teachers': teachers})

    def get_success_url(self):
        return self.object.get_detail_url()


class FacultyUpdateView(UpdateView):
    """
    Редактирование Факультета
    """

    model = Faculty
    template_name = 'main/faculties/update.html'
    form_class = FacultyUpdateForm

    def get_success_url(self):
        return self.object.get_detail_url()


class FacultyListView(ListView):
    """
    Список Факультетов
    """

    model = Faculty
    template_name = 'main/faculties/list.html'


class FacultyDetailView(DetailView):
    """
    Просмотр Факультета
    """

    model = Faculty
    template_name = 'main/faculties/detail.html'


class StatementCreateView(CreateView):
    """
    Создание Факультета
    """

    model = Statement
    template_name = 'main/statements/create.html'
    form_class = StatementCreateForm

    def get_success_url(self):
        return self.object.get_detail_url()


class StatementUpdateView(UpdateView):
    """
    Редактирование Факультета
    """

    model = Statement
    template_name = 'main/statements/update.html'
    form_class = StatementUpdateForm

    def get_success_url(self):
        return self.object.get_detail_url()


class StatementListView(ListView):
    """
    Список Факультетов
    """

    model = Statement
    template_name = 'main/statements/list.html'


class StatementDetailView(DetailView):
    """
    Просмотр Факультета
    """

    model = Statement
    template_name = 'main/statements/detail.html'

templates/main/departments/create.html
{% extends 'base.html' %}

{% block content %}
  <div class="container mt-5">
    <h2 class="mb-4">Создать новую кафедру</h2>

    <form method="post">
      {% csrf_token %}

      <div class="mb-3">
        <label for="id_name" class="form-label">Название кафедры</label>
        <input type="text" class="form-control" id="id_name" name="name" required>
      </div>

      <div class="mb-3">
        <label for="id_leader" class="form-label">Заведующий</label>
        <select class="form-select" id="id_leader" name="leader">
          {% for teacher in all_teachers %}
            <option value="{{ teacher.id }}">{{ teacher.first_name }} {{ teacher.last_name }}</option>
          {% endfor %}
        </select>
      </div>

      <div class="mb-3">
        <label for="id_faculty" class="form-label">Факультет</label>
        <select class="form-select" id="id_faculty" name="faculty">
          {% for faculty in object.faculty %}
            <option value="{{ faculty.id }}">{{ faculty.name }}</option>
          {% endfor %}
        </select>
      </div>

      <div class="mb-3">
        <label for="id_room" class="form-label">Номер комнаты</label>
        <input type="number" class="form-control" id="id_room" name="room" required>
      </div>

      <div class="mb-3">
        <label for="id_housing" class="form-label">Номер корпуса</label>
        <input type="number" class="form-control" id="id_housing" name="housing" required>
      </div>

      <div class="mb-3">
        <label for="id_phone" class="form-label">Номер телефона</label>
        <input type="text" class="form-control" id="id_phone" name="phone" required>
      </div>

      <div class="mb-3">
        <label for="id_teachers" class="form-label">Преподаватели</label>
        <select multiple class="form-select" id="id_teachers" name="teachers">
          {% for teacher in form.teachers.all %}
            <option value="{{ teacher.id }}">{{ teacher.first_name }} {{ teacher.last_name }}</option>
          {% endfor %}
        </select>
      </div>

      <button type="submit" class="btn btn-primary">Создать кафедру</button>
    </form>

    <div class="mt-3">
      <a href="{% url 'main:department-list' %}" class="btn btn-secondary">Отмена</a>
    </div>
  </div>
{% endblock %}

templates/main/departments/detail.html
{% extends 'base.html' %}

{% block content %}
  <div class="container mt-5">
    <h2 class="mb-4">Информация о кафедре</h2>

    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Название кафедры: {{ department.name }}</h5>
        <p class="card-text">Заведующий: {{ department.leader.first_name }} {{ department.leader.last_name }}</p>
        <p class="card-text">Факультет: {{ department.faculty.name }}</p>
        <p class="card-text">Номер комнаты: {{ department.room }}</p>
        <p class="card-text">Номер корпуса: {{ department.housing }}</p>
        <p class="card-text">Номер телефона: {{ department.phone }}</p>
        <p class="card-text">Преподаватели:</p>
        <ul>
          {% for teacher in department.teachers.all %}
            <li>{{ teacher.first_name }} {{ teacher.last_name }}</li>
          {% endfor %}
        </ul>
      </div>
    </div>

    <div class="mt-3">
      <a href="{% url 'main:department-list' %}" class="btn btn-primary">Вернуться к списку кафедр</a>
      <a href="{% url 'main:department-edit' object.pk %}" class="btn btn-warning">Редактировать</a>
    </div>
  </div>
{% endblock %}

templates/main/departments/list.html
{% extends 'base.html' %}

{% block content %}
  <div class="container mt-5">
    <div class="d-flex justify-content-between align-items-center mb-4">
      <h2 class="mb-4">Список кафедр</h2>
      <a href="{% url 'main:department-create' %}" class="btn btn-primary">Добавить кафедру</a>
    </div>


    <table class="table">
      <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Название кафедры</th>
        <th scope="col">Заведующий</th>
        <th scope="col">Факультет</th>
        <th scope="col">Номер комнаты</th>
        <th scope="col">Номер корпуса</th>
        <th scope="col">Номер телефона</th>
        <th scope="col">Преподаватели</th>
      </tr>
      </thead>
      <tbody>
      {% for department in object_list %}
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <td><a href="{% url 'main:department-detail' pk=department.pk %}">{{ department.name }}</a></td>
          <td>{{ department.leader.first_name }} {{ department.leader.last_name }}</td>
          <td>{{ department.faculty.name }}</td>
          <td>{{ department.room }}</td>
          <td>{{ department.housing }}</td>
          <td>{{ department.phone }}</td>
          <td>
            {% for teacher in department.teachers.all %}
              {{ teacher.first_name }} {{ teacher.last_name }}{% if not forloop.last %}, {% endif %}
            {% endfor %}
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

templates/main/departments/update.html
{% extends 'base.html' %}

{% block content %}
  <div class="container mt-5">
    <h2 class="mb-4">Редактировать информацию о кафедре</h2>

    <form method="post">
      {% csrf_token %}

      <div class="mb-3">
        <label for="id_name" class="form-label">Название кафедры</label>
        <input type="text" class="form-control" id="id_name" name="name" value="{{ department.name }}" required>
      </div>

      <div class="mb-3">
        <label for="id_leader" class="form-label">Заведующий</label>
        <select class="form-select" id="id_leader" name="leader">
          <option value="{{ department.leader.id }}" selected>{{ department.leader.first_name }} {{ department.leader.last_name }}</option>
          <!-- Добавьте другие варианты выбора для всех преподавателей -->
          {% for teacher in all_teachers %}
            <option value="{{ teacher.id }}">{{ teacher.first_name }} {{ teacher.last_name }}</option>
          {% endfor %}
        </select>
      </div>

      <div class="mb-3">
        <label for="id_faculty" class="form-label">Факультет</label>
        <select class="form-select" id="id_faculty" name="faculty">
          <option value="{{ department.faculty.id }}" selected>{{ department.faculty.name }}</option>
          <!-- Добавьте другие варианты выбора для всех факультетов -->
          {% for faculty in object.faculty.all %}
            <option value="{{ faculty.id }}">{{ faculty.name }}</option>
          {% endfor %}
        </select>
      </div>

      <div class="mb-3">
        <label for="id_room" class="form-label">Номер комнаты</label>
        <input type="number" class="form-control" id="id_room" name="room" value="{{ department.room }}" required>
      </div>

      <div class="mb-3">
        <label for="id_housing" class="form-label">Номер корпуса</label>
        <input type="number" class="form-control" id="id_housing" name="housing" value="{{ department.housing }}" required>
      </div>

      <div class="mb-3">
        <label for="id_phone" class="form-label">Номер телефона</label>
        <input type="text" class="form-control" id="id_phone" name="phone" value="{{ department.phone }}" required>
      </div>

      <div class="mb-3">
        <label for="id_teachers" class="form-label">Преподаватели</label>
        <select multiple class="form-select" id="id_teachers" name="teachers">
          {% for teacher in object.teachers.all %}
            <option value="{{ teacher.id }}" {% if teacher in department.teachers.all %}selected{% endif %}>{{ teacher.first_name }} {{ teacher.last_name }}</option>
          {% endfor %}
        </select>
      </div>

      <button type="submit" class="btn btn-primary">Сохранить изменения</button>
    </form>

    <div class="mt-3">
      <a href="{% url 'main:department-detail' department.pk %}" class="btn btn-secondary">Отмена</a>
    </div>
  </div>
{% endblock %}