base/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('peoples.urls')),
    path('main/', include('main.urls'))
]

main/urls.py
from django.urls import path
from main import views

app_name = 'main'

urlpatterns = [
    path('', views.DepartmentListView.as_view(), name='department-list'),
    path('departments/create/', views.DepartmentCreateView.as_view(), name='department-create'),
    path('departments/update/<int:pk>/', views.DepartmentUpdateView.as_view(), name='department-edit'),
    path('departments/detail/<int:pk>/', views.DepartmentDetailView.as_view(), name='department-detail'),
    path('faculties/', views.FacultyListView.as_view(), name='faculty-list'),
    path('faculties/create/', views.FacultyCreateView.as_view(), name='faculty-create'),
    path('faculties/update/<int:pk>/', views.FacultyUpdateView.as_view(), name='faculty-edit'),
    path('faculties/detail/<int:pk>/', views.FacultyDetailView.as_view(), name='faculty-detail'),
    path('statements/', views.StatementListView.as_view(), name='statement-list'),
    path('statements/create/', views.StatementCreateView.as_view(), name='statement-create'),
    path('statements/update/<int:pk>/', views.StatementUpdateView.as_view(), name='statement-edit'),
    path('statements/detail/<int:pk>/', views.StatementDetailView.as_view(), name='statement-detail'),
]

main/models.py
from django.db import models
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.functional import cached_property


class Faculty(models.Model):
    """
    Факультет
    """

    name = models.CharField('Название факультета', max_length=5000)
    leader = models.OneToOneField('peoples.Stuff', verbose_name='Декан', null=True, blank=True, on_delete=models.SET_NULL)
    room = models.PositiveIntegerField('Номер комнаты', default=1)
    housing = models.PositiveIntegerField('Номер корпуса', default=1)
    phone = models.CharField('Номер телефона', max_length=30, blank=True, default='Отсутствует')
    teachers = models.ManyToManyField('peoples.Stuff', verbose_name='Преподаватели', related_name='faculties')

    class Meta:
        verbose_name = 'Факультет'
        verbose_name_plural = 'Факультеты'
        ordering = ('-name',)

    def __str__(self):
        return self.name

    def get_detail_url(self):
        return reverse_lazy('main:faculty-detail', kwargs={'pk': self.pk})


class Department(models.Model):
    """
    Кафедра
    """

    name = models.CharField('Название кафедры', max_length=5000)
    leader = models.OneToOneField(
        'peoples.Stuff', verbose_name='Заведующий', related_name='department', null=True, blank=True, on_delete=models.SET_NULL
    )
    faculty = models.ForeignKey(
        'main.Faculty', verbose_name='Факультет', null=True, blank=True, on_delete=models.SET_NULL
    )
    room = models.PositiveIntegerField('Номер комнаты', default=1)
    housing = models.PositiveIntegerField('Номер корпуса', default=1)
    phone = models.CharField('Номер телефона', max_length=30, blank=True, default='Отсутствует')
    teachers = models.ManyToManyField('peoples.Stuff', verbose_name='Преподаватели', related_name='departments')

    class Meta:
        verbose_name = 'Кафедра'
        verbose_name_plural = 'Кафедры'
        ordering = ('-name',)

    def __str__(self):
        return self.name

    def get_detail_url(self):
        return reverse_lazy('main:department-detail', kwargs={'pk': self.pk})


class StudentGroup(models.Model):
    """
    Учебная группа
    """

    name = models.CharField('Название группы', max_length=5000)
    date_start = models.DateField('Дата поступления', default=timezone.now, blank=True)
    course = models.PositiveIntegerField('Курс', default=1),
    students = models.ManyToManyField('peoples.Student', verbose_name='Студенты', related_name='student_groups')

    class Meta:
        verbose_name = 'Учебная группа'
        verbose_name_plural = 'Учебные группы'
        ordering = ('-name',)

    def __str__(self):
        return self.name


class Statement(models.Model):
    """
    Ведомость
    """

    group = models.OneToOneField(
        'main.StudentGroup', verbose_name='Группа', related_name='statement', on_delete=models.CASCADE
    )
    student = models.OneToOneField(
        'peoples.Student', verbose_name='Студент', related_name='statement', on_delete=models.CASCADE
    )
    grade = models.PositiveIntegerField('Оценка', default=1)

    @cached_property
    def name(self):
        return f'Ведомость студента {self.student} группы {self.group}'

    class Meta:
        verbose_name = 'Ведомость'
        verbose_name_plural = 'Ведомости'
        ordering = ('-student',)

    def __str__(self):
        return self.name


    def get_detail_url(self):
        return reverse_lazy('main:statement-detail', kwargs={'pk': self.pk})

main/forms.py
from django import forms
from main.models import Department, Faculty, Statement


class DepartmentBaseForm(forms.ModelForm):
    """
    Базовая форма Кафедры
    """

    class Meta:
        model = Department
        fields = '__all__'


class DepartmentCreateForm(DepartmentBaseForm):
    """
    Форма Создание кафедры
    """

    pass


class DepartmentUpdateForm(DepartmentBaseForm):
    """
    Форма Редактирование кафедры
    """

    pass


class FacultyBaseForm(forms.ModelForm):
    """
    Базовая форма Факультета
    """

    class Meta:
        model = Faculty
        fields = '__all__'


class FacultyCreateForm(FacultyBaseForm):
    """
    Форма Создание Факультета
    """

    pass


class FacultyUpdateForm(FacultyBaseForm):
    """
    Форма Редактирование Факультета
    """

    pass


class StatementBaseForm(forms.ModelForm):
    """
    Базовая форма Ведомости
    """

    class Meta:
        model = Statement
        fields = '__all__'


class StatementCreateForm(StatementBaseForm):
    """
    Форма Создание Ведомости
    """

    pass


class StatementUpdateForm(StatementBaseForm):
    """
    Форма Редактирование Ведомости
    """

    pass

main/views.py
from django.views.generic import CreateView, UpdateView, ListView, DetailView

from main.forms import FacultyUpdateForm, FacultyCreateForm, DepartmentUpdateForm, DepartmentCreateForm, \
    StatementUpdateForm, StatementCreateForm
from main.models import Department, Faculty, Statement
from peoples.choices import StuffRole
from peoples.models import Stuff


class DepartmentCreateView(CreateView):
    """
    Создание Кафедры
    """

    model = Department
    template_name = 'main/departments/create.html'
    form_class = DepartmentCreateForm

    def get_success_url(self):
        return self.object.get_detail_url()


class DepartmentUpdateView(UpdateView):
    """
    Редактирование Кафедры
    """

    model = Department
    template_name = 'main/departments/update.html'
    form_class = DepartmentUpdateForm

    def get_success_url(self):
        return self.object.get_detail_url()


class DepartmentListView(ListView):
    """
    Список Кафедр
    """

    model = Department
    template_name = 'main/departments/list.html'


class DepartmentDetailView(DetailView):
    """
    Просмотр Кафедры
    """

    model = Department
    template_name = 'main/departments/detail.html'


class FacultyCreateView(CreateView):
    """
    Создание Факультета
    """

    model = Faculty
    template_name = 'main/faculties/create.html'
    form_class = FacultyCreateForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        teachers = Stuff.objects.filter(role=StuffRole.TEACHER)
        context.update({'teachers': teachers})

    def get_success_url(self):
        return self.object.get_detail_url()


class FacultyUpdateView(UpdateView):
    """
    Редактирование Факультета
    """

    model = Faculty
    template_name = 'main/faculties/update.html'
    form_class = FacultyUpdateForm

    def get_success_url(self):
        return self.object.get_detail_url()


class FacultyListView(ListView):
    """
    Список Факультетов
    """

    model = Faculty
    template_name = 'main/faculties/list.html'


class FacultyDetailView(DetailView):
    """
    Просмотр Факультета
    """

    model = Faculty
    template_name = 'main/faculties/detail.html'


class StatementCreateView(CreateView):
    """
    Создание Факультета
    """

    model = Statement
    template_name = 'main/statements/create.html'
    form_class = StatementCreateForm

    def get_success_url(self):
        return self.object.get_detail_url()


class StatementUpdateView(UpdateView):
    """
    Редактирование Факультета
    """

    model = Statement
    template_name = 'main/statements/update.html'
    form_class = StatementUpdateForm

    def get_success_url(self):
        return self.object.get_detail_url()


class StatementListView(ListView):
    """
    Список Факультетов
    """

    model = Statement
    template_name = 'main/statements/list.html'


class StatementDetailView(DetailView):
    """
    Просмотр Факультета
    """

    model = Statement
    template_name = 'main/statements/detail.html'

templates/main/faculties/create.html
{% extends 'base.html' %}

{% block content %}
  <div class="container mt-5">
    <h2 class="mb-4">Добавление нового факультета</h2>

    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}

      <div class="form-group">
        <label for="name">Название факультета:</label>
        <input type="text" class="form-control" id="name" name="name" required>
      </div>

      <div class="form-group">
        <label for="leader">Декан:</label>
        <select class="form-control" id="leader" name="leader">
          <option value="" selected>Выберите декана (необязательно)</option>
          {% for teacher in teachers %}
            <option value="{{ teacher.id }}">{{ teacher }}</option>
          {% endfor %}
        </select>
      </div>

      <div class="form-group">
        <label for="room">Номер комнаты:</label>
        <input type="number" class="form-control" id="room" name="room" value="1" required>
      </div>

      <div class="form-group">
        <label for="housing">Номер корпуса:</label>
        <input type="number" class="form-control" id="housing" name="housing" value="1" required>
      </div>

      <div class="form-group">
        <label for="phone">Номер телефона:</label>
        <input type="text" class="form-control" id="phone" name="phone" placeholder="Отсутствует" maxlength="30">
      </div>

      <div class="form-group">
        <label for="teachers">Преподаватели:</label>
        <select multiple class="form-control" id="teachers" name="teachers">
          {% for teacher in teachers %}
            <option value="{{ teacher.id }}">{{ teacher }}</option>
          {% endfor %}
        </select>
      </div>

      <button type="submit" class="btn btn-primary">Создать факультет</button>
    </form>
    <div class="mt-3">
      <a href="{% url 'main:faculty-list' %}" class="btn btn-secondary">Отмена</a>
    </div>
  </div>
{% endblock %}

templates/main/faculties/detail.html
{% extends 'base.html' %}

{% block content %}
  <div class="container mt-5">
    <h2 class="mb-4">Детали факультета: {{ faculty.name }}</h2>

    <dl class="row">
      <dt class="col-sm-3">Название факультета:</dt>
      <dd class="col-sm-9">{{ faculty.name }}</dd>

      <dt class="col-sm-3">Декан:</dt>
      <dd class="col-sm-9">{{ faculty.leader.full_name if faculty.leader else 'Отсутствует' }}</dd>

      <dt class="col-sm-3">Номер комнаты:</dt>
      <dd class="col-sm-9">{{ faculty.room }}</dd>

      <dt class="col-sm-3">Номер корпуса:</dt>
      <dd class="col-sm-9">{{ faculty.housing }}</dd>

      <dt class="col-sm-3">Номер телефона:</dt>
      <dd class="col-sm-9">{{ faculty.phone }}</dd>

      <dt class="col-sm-3">Преподаватели:</dt>
      <dd class="col-sm-9">
        {% if faculty.teachers.exists %}
          <ul>
            {% for teacher in faculty.teachers.all %}
              <li>{{ teacher.full_name }}</li>
            {% endfor %}
          </ul>
        {% else %}
          Отсутствуют
        {% endif %}
      </dd>
    </dl>
    <a href="{% url 'main:faculty-list' %}" class="btn btn-secondary">Вернуться к списку факультетов</a>
    <a href="{% url 'main:faculty-edit' object.pk %}" class="btn btn-warning">Редактировать</a>
  </div>
{% endblock %}

templates/main/faculties/list.html
{% extends 'base.html' %}

{% block content %}
  <div class="container mt-5">
    <div class="d-flex justify-content-between align-items-center mb-4">
      <h2 class="mb-4">Список факультетов</h2>
      <a href="{% url 'main:faculty-create' %}" class="btn btn-primary">Добавить факультет</a>
    </div>

    <table class="table table-bordered">
      <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Название факультета</th>
        <th scope="col">Декан</th>
        <th scope="col">Номер комнаты</th>
        <th scope="col">Номер корпуса</th>
        <th scope="col">Номер телефона</th>
        <th scope="col">Преподаватели</th>
      </tr>
      </thead>
      <tbody>
      {% for faculty in object_list %}
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <td>{{ faculty.name }}</td>
          <td>{% if faculty.leader %}{{ faculty.leader }}{% else %}Отсутствует{% endif %}</td>
          <td>{{ faculty.room }}</td>
          <td>{{ faculty.housing }}</td>
          <td>{{ faculty.phone }}</td>
          <td>
            {% if faculty.teachers.exists %}
              {% for teacher in faculty.teachers.all %}
                {{ teacher.full_name }}{% if not forloop.last %}, {% endif %}
              {% endfor %}
            {% else %}
              Отсутствуют
            {% endif %}
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

templates/main/faculties/update.html
{% extends 'base.html' %}

{% block content %}
  <div class="container mt-5">
    <h2 class="mb-4">Редактирование факультета</h2>

    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}

      <div class="form-group">
        <label for="name">Название факультета:</label>
        <input type="text" class="form-control" id="name" name="name" value="{{ faculty.name }}" required>
      </div>

      <div class="form-group">
        <label for="leader">Декан:</label>
        <select class="form-control" id="leader" name="leader">
          <option value="" selected>Выберите декана (необязательно)</option>
          {% for teacher in object.teachers.all %}
            <option value="{{ teacher.id }}"
                    {% if faculty.leader == teacher %}selected{% endif %}>{{ teacher}}</option>
          {% endfor %}
        </select>
      </div>

      <div class="form-group">
        <label for="room">Номер комнаты:</label>
        <input type="number" class="form-control" id="room" name="room" value="{{ faculty.room }}" required>
      </div>

      <div class="form-group">
        <label for="housing">Номер корпуса:</label>
        <input type="number" class="form-control" id="housing" name="housing" value="{{ faculty.housing }}" required>
      </div>

      <div class="form-group">
        <label for="phone">Номер телефона:</label>
        <input type="text" class="form-control" id="phone" name="phone" value="{{ faculty.phone }}" maxlength="30">
      </div>

      <div class="form-group">
        <label for="teachers">Преподаватели:</label>
        <select multiple class="form-control" id="teachers" name="teachers">
          {% for teacher in teachers %}
            <option value="{{ teacher.id }}"
                    {% if teacher in faculty.teachers.all %}selected{% endif %}>{{ teacher }}</option>
          {% endfor %}
        </select>
      </div>

      <button type="submit" class="btn btn-primary">Сохранить изменения</button>
    </form>
    <div class="mt-3">
      <a href="{% url 'main:department-list' %}" class="btn btn-secondary">Отмена</a>
    </div>
  </div>
{% endblock %}